### ISSUE TITLE
WARZONE API

### ISSUE THREAD

**Issue by ghost** [TrackerNetwork/TRN.Developers#32]
Any ETA?

**Comment by lwansbrough** [comment]
Rate limits are super tight on this API so we're probably not going to be able to provide capacity to other devs

**Comment by SquatchHunter** [comment]
G'day

as Iwansbrough said, it's not only a capacity thing but slightly redundent as the API we are utilising is also publicly available for use, direct from Activision, if you need some assistance on how to utilise that API, [CallOfDuty.py](https://github.com/EthanC/CallofDuty.py) has a basic method for authentication and grabbing data from the API.

Thanks,
Squatch_
Community Support & Discord Mod for TheTrackerNetwork

**Comment by Reptiluka** [comment]
Hi @SquatchHunter ,
it is the API you used for cod.tracker.gg ?
Do you know one place where it listing all routes for the api ?
Or also do you know a javascript version equivalent of the python version mentionned before ?

Thank you ! :)

**Comment by revalgovender** [comment]
Hi @SquatchHunter 

Thanks for informing us about [CallOfDuty.py](https://github.com/EthanC/CallofDuty.py). I spent a few hours playing around with it. Most of the calls work, which is great.

The one thing I need working is the matches endpoint. I want to pull all users who were in my lobby. Unfortunately, the [match endpoints](https://github.com/EthanC/CallofDuty.py/blob/4b9436aaddb480f7e3ed04d8ef2ceb7dc32d5361/callofduty/client.py#L842) fail (I receive 500 errors). I heard Call of Duty stopped giving away this data, but you guys manage to pull this data. COD Tracker shows everyone in the match ([Example](https://cod.tracker.gg/warzone/match/9698009010178892589?handle=Empire_Crusher))

My goal is determine the average KD of the lobby. I can't do this with [CallOfDuty.py](https://github.com/EthanC/CallofDuty.py) due to the 500 error from the server.

**Comment by JaySmithPython** [comment]
@revalgovender I was having the same problems with a lot of the API calls and there are a couple things I can tell you to save a lot of time.  

- Auth your connection with the client.Login call
- Get your player profile with the player.profile call
- Now the trick is that with the V1.2.2 you need to use the clinet.GetFullMatch call
- The GetMatch and GetMatchDetails return a timeout error
- GetFullMatch returns a heavily nested list of dictionaries with all of the data you are looking for 

![Code_KuLaPdZZF8](https://user-images.githubusercontent.com/62914488/104267253-8033e900-544e-11eb-8028-d4109b1f22f3.png)

**Comment by witchpiggie** [comment]
Even if the API rate limiting on the COD side of things is pretty tight (and has the same information as publicly available), wouldn't it still be beneficial to provide the stats from your own API (at your set rate limits) for people who might want to integrate several games from your API? It would be far easier to implement information for several games, if I can use one API source, rather than figuring out multiple. Also, you provide a real API to work with, which is far more comfortable than dealing with this nonsense that COD makes people do. (My level of frustration with finding a workable API for this information is beyond measure).

**Comment by bladefist** [comment]
@witchpiggie agreed. We're not allowed to, that's the issue, it's not a matter if we want to or not.  We are providing APIs where possible for a unified api experience.

**Comment by revgovmade** [comment]
> @revalgovender I was having the same problems with a lot of the API calls and there are a couple things I can tell you to save a lot of time.
> 
> * Auth your connection with the client.Login call
> * Get your player profile with the player.profile call
> * Now the trick is that with the V1.2.2 you need to use the clinet.GetFullMatch call
> * The GetMatch and GetMatchDetails return a timeout error
> * GetFullMatch returns a heavily nested list of dictionaries with all of the data you are looking for
> 
> ![Code_KuLaPdZZF8](https://user-images.githubusercontent.com/62914488/104267253-8033e900-544e-11eb-8028-d4109b1f22f3.png)

Hey man. I am now using the `GetFullMatch` call. Thanks so much!
I am so confused about your code snippet `Lobby_Stats_Clean['kdRatio'].desacribe()`.
In your snippet, what is `Lobby_Stats_Clean`?

I get a response of all the players in the match
<img width="465" alt="Screenshot 2021-08-09 at 19 32 51" src="https://user-images.githubusercontent.com/54805885/128756219-39229031-4d1c-463f-9c08-fc6e73827d71.png">

**Comment by revalgovender** [comment]
> @revalgovender I was having the same problems with a lot of the API calls and there are a couple things I can tell you to save a lot of time.
> 
> * Auth your connection with the client.Login call
> * Get your player profile with the player.profile call
> * Now the trick is that with the V1.2.2 you need to use the clinet.GetFullMatch call
> * The GetMatch and GetMatchDetails return a timeout error
> * GetFullMatch returns a heavily nested list of dictionaries with all of the data you are looking for
> 
> ![Code_KuLaPdZZF8](https://user-images.githubusercontent.com/62914488/104267253-8033e900-544e-11eb-8028-d4109b1f22f3.png)

Hey man. I am now using the GetFullMatch call. Thanks so much!
I am so confused about your code snippet Lobby_Stats_Clean['kdRatio'].desacribe().
In your snippet, what is Lobby_Stats_Clean?

I get a response of all the players in the match
![unnamed](https://user-images.githubusercontent.com/20873199/128758341-00fe9642-95fb-40ee-8708-d9445c1f1570.png)
